package com.verizon.cache.domain;

// Generated Oct 7, 2016 9:52:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * GetFromCache generated by hbm2java
 */
public class GetFromCache implements java.io.Serializable {

	private GetFromCacheId id;

	public GetFromCache() {
	}

	public GetFromCache(GetFromCacheId id) {
		this.id = id;
	}

	public GetFromCacheId getId() {
		return this.id;
	}

	public void setId(GetFromCacheId id) {
		this.id = id;
	}

}
