package com.verizon.cache.domain;

// Generated Oct 7, 2016 9:52:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * GetFromCacheId generated by hbm2java
 */
public class GetFromCacheId implements java.io.Serializable {

	private String htmlFileName;
	private String fieldId;
	private String parameterName;

	public GetFromCacheId() {
	}

	public GetFromCacheId(String htmlFileName, String fieldId,
			String parameterName) {
		this.htmlFileName = htmlFileName;
		this.fieldId = fieldId;
		this.parameterName = parameterName;
	}

	public String getHtmlFileName() {
		return this.htmlFileName;
	}

	public void setHtmlFileName(String htmlFileName) {
		this.htmlFileName = htmlFileName;
	}

	public String getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(String fieldId) {
		this.fieldId = fieldId;
	}

	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GetFromCacheId))
			return false;
		GetFromCacheId castOther = (GetFromCacheId) other;

		return ((this.getHtmlFileName() == castOther.getHtmlFileName()) || (this
				.getHtmlFileName() != null
				&& castOther.getHtmlFileName() != null && this
				.getHtmlFileName().equals(castOther.getHtmlFileName())))
				&& ((this.getFieldId() == castOther.getFieldId()) || (this
						.getFieldId() != null && castOther.getFieldId() != null && this
						.getFieldId().equals(castOther.getFieldId())))
				&& ((this.getParameterName() == castOther.getParameterName()) || (this
						.getParameterName() != null
						&& castOther.getParameterName() != null && this
						.getParameterName()
						.equals(castOther.getParameterName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getHtmlFileName() == null ? 0 : this.getHtmlFileName()
						.hashCode());
		result = 37 * result
				+ (getFieldId() == null ? 0 : this.getFieldId().hashCode());
		result = 37
				* result
				+ (getParameterName() == null ? 0 : this.getParameterName()
						.hashCode());
		return result;
	}

}
