package com.verizon.cache.domain;

// Generated Oct 7, 2016 9:52:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PushToCache generated by hbm2java
 */
public class PushToCache implements java.io.Serializable {

	private PushToCacheId id;

	public PushToCache() {
	}

	public PushToCache(PushToCacheId id) {
		this.id = id;
	}

	public PushToCacheId getId() {
		return this.id;
	}

	public void setId(PushToCacheId id) {
		this.id = id;
	}

}
